### ISSUE TITLE
Error after -- vagrant up -- command 

### ISSUE THREAD

**Issue by ilol** [buskamuza/magento2-product-vagrant#4]
1. Box installed on Windows 7 x64 
2. vagrant up
3. error
   ![image](https://cloud.githubusercontent.com/assets/6792285/5921097/0505fe66-a64a-11e4-8423-8a8c033a015a.png)

**Comment by buskamuza** [comment]
Looks like VirtualBox has some issue with this host-only adapter.
https://www.virtualbox.org/ticket/8362

Did you try restart VirtrualBox and then "vagrant up" again?
And do you have the latest VirtualBox? Maybe re-installation (if it's acceptable) can help.

**Comment by skukla** [comment]
Ah – just FYI, I didn’t submit or send this original email.  That’s why I wrote you about it – it seemed strange to me.

Thanks,

Steve Kukla
Technical Trainer

eBay Enterprise
310.945.0345 x 1347
skukla@ebay.com   ebayenterprise.com
Skype: steve.kukla
LinkedIn: www.linkedin.com/in/stevenkuklahttp://www.linkedin.com/in/stevenkukla

[logo-email.gif]

**Comment by skukla** [comment]
Hi,

I'm not sure where I should report this, but I thought maybe you could help:

==> default: Installing Widgets:
==> default: ======================================================================
==> default:    The application has thrown an exception!
==> default: ======================================================================
==> default:  Zend_Db_Statement_Exception
==> default:  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`widget_instance`, CONSTRAINT `FK_WIDGET_INSTANCE_THEME_ID_THEME_THEME_ID` FOREIGN KEY (`theme_id`) REFERENCES `theme` (`theme_id`) ON DELETE CASCADE ON UPDATE CASCADE), query was: INSERT INTO `widget_instance` (`instance_type`, `title`, `store_ids`, `widget_parameters`) VALUES (?, ?, ?, ?)
==> default: ----------------------------------------------------------------------
==> default: /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
==> default: #0 /var/www/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
==> default: #1 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
==> default: #2 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
==> default: #3 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `wi...', Array)
==> default: #4 /var/www/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(427): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO`wi...', Array)
==> default: #5 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `wi...', Array)
==> default: #6 /var/www/magento2/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(428): Zend_Db_Adapter_Abstract->insert('widget_instance', Array)
==> default: #7 /var/www/magento2/lib/internal/Magento/Framework/Model/AbstractModel.php(393): Magento\Framework\Model\Resource\Db\AbstractDb->save(Object(Magento\Widget\Model\Widget\Instance))
==> default: #8 /var/www/magento2/dev/tools/Magento/Tools/SampleData/Module/Widget/Setup/CmsBlock.php(151): Magento\Framework\Model\AbstractModel->save()
==> default: #9 /var/www/magento2/dev/tools/Magento/Tools/SampleData/Helper/PostInstaller.php(86): Magento\Tools\SampleData\Module\Widget\Setup\CmsBlock->run()
==> default: #10 /var/www/magento2/dev/tools/Magento/Tools/SampleData/Installer.php(88): Magento\Tools\SampleData\Helper\PostInstaller->run()
==> default: #11 /var/www/magento2/setup/src/Magento/Setup/Model/SampleData.php(75): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
==> default: #12 /var/www/magento2/setup/src/Magento/Setup/Model/Installer.php(893): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\ConsoleLogger), 'admin')
==> default: #13 [internal function]: Magento\Setup\Model\Installer->installSampleData(Object(Zend\Stdlib\Parameters))
==> default: #14 /var/www/magento2/setup/src/Magento/Setup/Model/Installer.php(293): call_user_func_array(Array, Array)
==> default: #15 /var/www/magento2/setup/src/Magento/Setup/Controller/ConsoleController.php(359): Magento\Setup\Model\Installer->install(Object(Zend\Stdlib\Parameters))
==> default: #16 /var/www/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\ConsoleController->installAction()
==> default: #17 /var/www/magento2/setup/src/Magento/Setup/Controller/ConsoleController.php(343): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
==> default: #18 [internal function]: Magento\Setup\Controller\ConsoleController->onDispatch(Object(Zend\Mvc\MvcEvent))
==> default: #19 /var/www/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
==> default: #20 /var/www/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
==> default: #21 /var/www/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
==> default: #22 /var/www/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
==> default: #23 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
==> default: #24 /var/www/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
==> default: #25 /var/www/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
==> default: #26 /var/www/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
==> default: #27 /var/www/magento2/setup/index.php(25): Zend\Mvc\Application->run()
==> default: #28 {main}
==> default: ======================================================================
==> default:    Previous Exception(s):
==> default: ======================================================================
==> default:  PDOException
==> default:  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`widget_instance`, CONSTRAINT`FK_WIDGET_INSTANCE_THEME_ID_THEME_THEME_ID`FOREIGN KEY (`theme_id`) REFERENCES`theme`(`theme_id`) ON DELETE CASCADE ON UPDATE CASCADE)
==> default: ----------------------------------------------------------------------
==> default: /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
==> default: #0 /var/www/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
==> default: #1 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
==> default: #2 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
==> default: #3 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO`wi...', Array)
==> default: #4 /var/www/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(427): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `wi...', Array)
==> default: #5 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO`wi...', Array)
==> default: #6 /var/www/magento2/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(428): Zend_Db_Adapter_Abstract->insert('widget_instance', Array)
==> default: #7 /var/www/magento2/lib/internal/Magento/Framework/Model/AbstractModel.php(393): Magento\Framework\Model\Resource\Db\AbstractDb->save(Object(Magento\Widget\Model\Widget\Instance))
==> default: #8 /var/www/magento2/dev/tools/Magento/Tools/SampleData/Module/Widget/Setup/CmsBlock.php(151): Magento\Framework\Model\AbstractModel->save()
==> default: #9 /var/www/magento2/dev/tools/Magento/Tools/SampleData/Helper/PostInstaller.php(86): Magento\Tools\SampleData\Module\Widget\Setup\CmsBlock->run()
==> default: #10 /var/www/magento2/dev/tools/Magento/Tools/SampleData/Installer.php(88): Magento\Tools\SampleData\Helper\PostInstaller->run()
==> default: #11 /var/www/magento2/setup/src/Magento/Setup/Model/SampleData.php(75): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
==> default: #12 /var/www/magento2/setup/src/Magento/Setup/Model/Installer.php(893): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\ConsoleLogger), 'admin')
==> default: #13 [internal function]: Magento\Setup\Model\Installer->installSampleData(Object(Zend\Stdlib\Parameters))
==> default: #14 /var/www/magento2/setup/src/Magento/Setup/Model/Installer.php(293): call_user_func_array(Array, Array)
==> default: #15 /var/www/magento2/setup/src/Magento/Setup/Controller/ConsoleController.php(359): Magento\Setup\Model\Installer->install(Object(Zend\Stdlib\Parameters))
==> default: #16 /var/www/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\ConsoleController->installAction()
==> default: #17 /var/www/magento2/setup/src/Magento/Setup/Controller/ConsoleController.php(343): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
==> default: #18 [internal function]: Magento\Setup\Controller\ConsoleController->onDispatch(Object(Zend\Mvc\MvcEvent))
==> default: #19 /var/www/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
==> default: #20 /var/www/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
==> default: #21 /var/www/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
==> default: #22 /var/www/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
==> default: #23 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
==> default: #24 /var/www/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
==> default: #25 /var/www/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
==> default: #26 /var/www/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
==> default: #27 /var/www/magento2/setup/index.php(25): Zend\Mvc\Application->run()
==> default: #28 {main}

Thanks,

Steve Kukla
Technical Trainer

eBay Enterprise
310.945.0345 x 1347
skukla@ebay.com   ebayenterprise.com
Skype: steve.kukla
LinkedIn: www.linkedin.com/in/stevenkuklahttp://www.linkedin.com/in/stevenkukla

[logo-email.gif]

**Comment by buskamuza** [comment]
@skukla , you can open new issue, if you want :)
Just updated the installation script to download the latest version of Sample Data. But still could not successfully install it - getting the same error.
